### ISSUE TITLE
Release to ROS buildfarm

### ISSUE THREAD

**Issue by Nobleans** [QuanergySystems/quanergy_client_ros#9] opened 2020-07-15 11:42 UTC
Could this package be released to the ROS buildfarm? This would greatly simplify the package installation. Now this package has quite a a-typical setup with regards to all other ROS drivers. Which makes is a maintenance effort from our side.

(Please also take into consideration a marketing aspect, packages that are easy found in the ROS community are free publicity for your hardware).

**Comment by rossctaylor** [comment] 2020-08-14 23:09
@Nobleans - We have made the repositories public. Sorry for being slow but we had a significant update in work and wanted to get that done first. We agree with you that making this available on the ROS build farm is a great idea and would certainly appreciate the help.

**Comment by Timple** [comment] 2020-08-24 05:22
↖ _This was the face behind the @Nobleans messages._

Great news! And thank you for taking the effort.

Did you already try to follow the first tutorial to get the sdk released?

**Comment by rossctaylor** [comment] 2020-08-24 17:47
@Timple - No, we haven't tried to do the release yet. I'll try to find some cycles but not sure how quickly we'll get to it.

**Comment by Timple** [comment] 2020-11-03 08:14
Hi, just a check-up. Did this end up on a backlog somewhere? :slightly_smiling_face:

**Comment by rossctaylor** [comment] 2020-11-03 15:00
Yes but it isn't a top priority for us right now. Sorry! FYI...feel free to reach out to your sales rep. Get sales excited and it's easier for me to free up resources. 😁

**Comment by Timple** [comment] 2021-05-07 08:31
Would you mind if I tried to release it?

**Comment by rossctaylor** [comment] 2021-05-09 21:35
@Timple - it would be great if you could work on it. I started looking into it and decided to address some other issues and PRs first but working in parallel should be fine. 

If you need me to do anything specifically, let me know or submit appropriate PRs. Thanks!

**Comment by rossctaylor** [comment] 2021-05-18 13:19
The merged tickets don't quite solve the issue. It still has some issues with include directories. Issue can be seen using the following Dockerfile:

`FROM ros:noetic
RUN mkdir -p ws/src
WORKDIR ws
RUN apt-get update -qq && apt-get install -qqy python3-catkin-tools python3-osrf-pycommon git
# Install dependencies listed in the package.xml files manually (instead of rosdep) to speed up dockerfile
RUN apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -qqy libpcl-dev libboost-all-dev ros-*-sensor-msgs ros-*-pcl-ros

RUN bash -c 'source /opt/ros/*/setup.bash && catkin init'
RUN git clone -b catkin-support https://github.com/nobleo/quanergy_client src/quanergy_client
RUN git clone -b fix/dependencies https://github.com/nobleo/quanergy_client_ros src/quanergy_client_ros
RUN bash -c 'source /opt/ros/*/setup.bash && catkin build'`

**Comment by Timple** [comment] 2021-05-18 13:41
After the merge the problem of course also reproduces with this repos devel branch:

```Dockerfile
FROM ros:noetic
RUN mkdir -p ws/src
WORKDIR ws
RUN apt-get update -qq && apt-get install -qqy python3-catkin-tools python3-osrf-pycommon git
# Install dependencies listed in the package.xml files manually (instead of rosdep) to speed up dockerfile
RUN apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -qqy libpcl-dev libboost-all-dev ros-*-sensor-msgs ros-*-pcl-ros

RUN git clone -b devel https://github.com/QuanergySystems/quanergy_client src/quanergy_client
RUN git clone -b devel https://github.com/QuanergySystems/quanergy_client_ros src/quanergy_client_ros
RUN bash -c 'source /opt/ros/*/setup.bash && catkin build'
```

**Comment by rossctaylor** [comment] 2021-06-08 22:23
@Timple https://github.com/QuanergySystems/quanergy_client/pull/27 fixes the build issue.

**Comment by Timple** [comment] 2021-06-09 07:29
So it does, thanks!

**Comment by rossctaylor** [comment] 2021-07-14 00:25
PRs for quanergy_client:
https://github.com/ros/rosdistro/pull/30189
https://github.com/ros/rosdistro/pull/30190

I think everything there is ok. As far as I can tell, I've to wait on that to be completed to do quanergy_client_ros because of the dependency.

**Comment by Timple** [comment] 2021-07-16 05:36
Awesome, you don't have to wait for the release to be completed though. The PR merged is enough to release `quanergy_client_ros`.

**Comment by Timple** [comment] 2021-07-16 05:44
The quanergy_client can also already be released for the active ROS2 distributions `foxy`, `galactic` and `rolling`. As the library is ROS-independent.

**Comment by rossctaylor** [comment] 2021-07-16 20:56
https://github.com/ros/rosdistro/pull/30242
https://github.com/ros/rosdistro/pull/30243

I'll address ROS 2 stuff on that ticket.

**Closed by rossctaylor** 2021-07-16 20:56 UTC
Labels: enhancement
